name: Simple Test Template
description: A simple template to test issue creation
title: "[Test]: "
labels: ["test"]
assignees: []

body:
  - type: input
    id: test-field
    attributes:
      label: Test Field
      description: Just a test field that says hollow
      placeholder: Enter something here...
      value: hello
