name: AI Issue Triage Gate 1
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read
  models: read   # Required for GitHub Models
  actions: write  # Required to trigger other workflows

jobs:
  # Job: Triage the issue to determine if it's legitimate
  triage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Use AI to classify the issue as legit or not_legit
      - name: Use GitHub Models to classify issue
        id: classify
        uses: actions/ai-inference@v1
        with:
          prompt: |
            You are triaging issues for the Djowda User App platform. Analyze this issue against our template requirements:
            
            REQUIRED for "legit" classification:
            - Issue Type must be selected (🐞 Bug Report, ✨ Feature Request, or 🛠 Improvement)
            - Description must be clear and meaningful (not just "doesn't work" or similar)
            - Related Component must be specified (🛒 Catalog, 📦 Orders, 👤 Account, 🔔 Notifications, ⚙️ Other)
            
            For BUG REPORTS specifically, also check:
            - If it's a bug, Steps to Reproduce should be provided
            - Expected vs Actual Behavior should be described
            
            SPAM indicators (mark as "not_legit"):
            - Generic/templated text unrelated to Djowda app
            - Promotional content or links
            - Nonsensical or AI-generated content
            - Empty or minimal descriptions like "fix this" or "doesn't work"
            
            Issue Title: ${{ github.event.issue.title }}
            Issue Body: ${{ github.event.issue.body }}
            
            Analyze the completeness and legitimacy. Respond with exactly one word: legit or not_legit
          system-prompt: You are a helpful assistant that triages GitHub issues for the Djowda User App. Focus on ensuring issues follow the template structure and provide sufficient detail for developers to act on.
          model: openai/gpt-4o-mini
          temperature: 0.2

      # Step 2: Process legitimate issues
      - name: Comment for legit issue
        if: contains(steps.classify.outputs.response, 'legit') && !contains(steps.classify.outputs.response, 'not_legit')
        uses: actions/github-script@v7
        with:
          script: |
            // Post initial validation comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<p align="center">
              <img src="https://raw.githubusercontent.com/Moses-Code-Dev/Djowda-UserApp/main/.github/assets/djowda-logo.png" width="120" />
            </p>

            👋 Hi @${{ github.event.issue.user.login }}!  
            Thanks for your contribution to the Djowda platform! 🎉  
            Your issue has been marked as **valid**. Analyzing for enrichment... 🔍`
            })

      # Step 3: Add triaged label for legitimate issues
      - name: Add label as triaged
        if: contains(steps.classify.outputs.response, 'legit') && !contains(steps.classify.outputs.response, 'not_legit')
        uses: actions/github-script@v7
        with:
          script: |
            // Add the 'triaged' label to mark this issue as validated
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triaged']
            })
            
            // Remove 'needs-info' label if it exists
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'needs-info'
            }).catch(() => {
              console.log('needs-info label not found, skipping removal')
            })

      # Step 4: Trigger Gate 2 workflow for legitimate issues (ROBUST VERSION)
      - name: Prepare issue data
        if: contains(steps.classify.outputs.response, 'legit') && !contains(steps.classify.outputs.response, 'not_legit')
        id: prepare_data
        run: |
          # Escape and prepare issue data for workflow dispatch
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Escape special characters for JSON
          ISSUE_TITLE_ESCAPED=$(echo "$ISSUE_TITLE" | jq -Rs .)
          ISSUE_BODY_ESCAPED=$(echo "$ISSUE_BODY" | jq -Rs .)
          
          # Set outputs
          echo "issue_title=$ISSUE_TITLE_ESCAPED" >> $GITHUB_OUTPUT
          echo "issue_body=$ISSUE_BODY_ESCAPED" >> $GITHUB_OUTPUT
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

      - name: Trigger Gate 2 Enrichment Workflow
        if: contains(steps.classify.outputs.response, 'legit') && !contains(steps.classify.outputs.response, 'not_legit')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Trigger the Gate 2 workflow using workflow_dispatch
            try {
              const issueNumber = '${{ steps.prepare_data.outputs.issue_number }}';
              const issueTitle = JSON.parse(${{ steps.prepare_data.outputs.issue_title }});
              const issueBody = JSON.parse(${{ steps.prepare_data.outputs.issue_body }});
            
              console.log('Triggering Gate 2 for issue #' + issueNumber);
            
              const result = await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'ai-issue-enrichment-gate2.yml',
                ref: 'main',
                inputs: {
                  issue_number: issueNumber,
                  issue_title: issueTitle,
                  issue_body: issueBody
                }
              });
            
              console.log('Successfully triggered Gate 2 workflow for issue #' + issueNumber);
            } catch (error) {
              console.error('Failed to trigger Gate 2 workflow:', error);
            
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `⚠️ Automatic enrichment couldn't be triggered. A maintainer will review and label this issue manually.`
              })
            }

      # Step 5: Handle non-legitimate issues
      - name: Comment for not legit issue
        if: contains(steps.classify.outputs.response, 'not_legit')
        uses: actions/github-script@v7
        with:
          script: |
            // Post a comment requesting more information for incomplete issues
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<p align="center">
              <img src="https://raw.githubusercontent.com/Moses-Code-Dev/Djowda-UserApp/main/.github/assets/djowda-logo.png" width="120" />
            </p>

            ⚠️ Hi @${{ github.event.issue.user.login }}!  
            Thanks for opening an issue! It looks like some important details may be missing or incomplete.

            Please ensure your issue includes:

            ✅ **Issue Type** - Select Bug Report, Feature Request, or Improvement  
            ✅ **Clear Description** - Explain the problem or idea in detail  
            ✅ **Related Component** - Choose which part of the app (🛒 Catalog, 📦 Orders, 👤 Account, etc.)

            For Bug Reports, also include:  
            🔍 **Steps to Reproduce** - How can we recreate the issue?  
            📋 **Expected vs Actual Behavior** - What should happen vs what actually happens?  
            📱 **Device Info** - Your device model and Android/iOS version

            Please update your issue using our template and we'll review it promptly! 🚀`
            })

      # Step 6: Add needs-info label for non-legitimate issues
      - name: Add label as needs-info
        if: contains(steps.classify.outputs.response, 'not_legit')
        uses: actions/github-script@v7
        with:
          script: |
            // Add 'needs-info' label to track incomplete issues
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-info']
            })
            
            // Remove 'triaged' label if it exists
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'triaged'
            }).catch(() => {
              console.log('triaged label not found, skipping removal')
            })

      # Step 7: Handle AI classification errors
      - name: Handle classification errors
        if: ${{ !contains(steps.classify.outputs.response, 'legit') && !contains(steps.classify.outputs.response, 'not_legit') }}
        uses: actions/github-script@v7
        with:
          script: |
            // Log the error and post a fallback comment
            console.log('AI classification failed or returned unexpected result:', '${{ steps.classify.outputs.response }}')
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `<p align="center">
              <img src="https://raw.githubusercontent.com/Moses-Code-Dev/Djowda-UserApp/main/.github/assets/djowda-logo.png" width="120" />
            </p>

            🤖 Hi @${{ github.event.issue.user.login }}!  
            Our AI triage is temporarily unavailable. A maintainer will review this issue manually. Thank you for your patience! 🙏`
            })